"""Chunking: the corpus-wide guarantees, and the identity with what the embedder was chosen on.

The guarantees run over the real vendored catalog rather than a miniature of it, for the reason
the loader's tests give. Synthetic controls appear only for the shapes the pinned release does
not contain — a live control with no prose, a control carrying one of the two included parts, a
part without an id — and each of those says so.

The first test is the one worth reading. `tools/bakeoff/prepare_corpus.py` is frozen as the
record of what the embedding comparison measured, and this chunker is a re-implementation of the
same rule against the typed objects rather than an import of it. Asserting that the two produce
byte-identical text is what turns "the shipped corpus is the corpus the model was chosen on"
from a claim in a document into something that fails a build.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from warrant.catalog_pin import get_catalog_pin
from warrant.ingest.catalog import Catalog, Control, Group, Part, get_catalog
from warrant.ingest.chunker import (
    CHUNKER_VERSION,
    Chunk,
    ChunkingError,
    chunk_catalog,
    chunker_fingerprint,
)
from warrant.ingest.control_ids import ControlIndex, get_control_index
from warrant.ingest.parameters import ParameterResolver

# The corpus the embedding comparison was run over, generated by the frozen script under
# `tools/`. Read here rather than restated: the point of the comparison is undermined by a test
# that checks the chunker against a copy of its own output.
MEASURED_CORPUS = Path(__file__).resolve().parents[2] / "tools" / "bakeoff" / "corpus.jsonl"

# The digest of every field of every chunk the pinned catalog produces. Pinned so that a change
# to assembly, to whitespace handling or to which controls get a chunk fails here rather than
# reaching the corpus unannounced; the fix is to bump CHUNKER_VERSION deliberately, or to revert.
EXPECTED_FINGERPRINT = "a74013c5e64c7e8097a74b15ac122a21fd7e2075e42af6716f66bb6b498d1c00"

# Every live control has exactly one `_smt` part and one `_gdn` part, so the corpus has one part
# path. Stated as a constant because a second value appearing is a fact about the catalog rather
# than a failure of the chunker, and the message should say which.
ONLY_PART_PATH = "smt+gdn"


@pytest.fixture(scope="module")
def catalog() -> Catalog:
    return get_catalog()


@pytest.fixture(scope="module")
def index() -> ControlIndex:
    return get_control_index()


@pytest.fixture(scope="module")
def chunks(catalog: Catalog) -> tuple[Chunk, ...]:
    return chunk_catalog(catalog)


def test_the_chunker_reproduces_the_corpus_the_embedder_was_measured_on(
    chunks: tuple[Chunk, ...],
) -> None:
    """Byte-for-byte across all 1,014 documents, against the frozen bake-off script's output.

    Breaking this means one of three things, and none of them is "adjust the expected value":
    the chunking changed and CHUNKER_VERSION has to be bumped and the corpus re-embedded, the
    recall figures in `docs/decisions/embedder.md` no longer describe the shipped corpus and the
    comparison has to be re-run, or the change was unintended and belongs reverted.
    """
    measured = {
        document["id"]: document["text"]
        for document in (
            json.loads(line) for line in MEASURED_CORPUS.read_text(encoding="utf-8").splitlines()
        )
    }

    assert measured
    assert {chunk.control_id: chunk.text for chunk in chunks} == measured


def test_every_chunk_names_a_control_this_catalog_contains(
    chunks: tuple[Chunk, ...], index: ControlIndex
) -> None:
    """The criterion the whole module exists for, over the full corpus and not a sample.

    Looked up by canonical id alone rather than through `resolve`, which also accepts labels: a
    chunk whose `control_id` held a label would still resolve, and would still be the thing this
    is written to catch.

    The label and the title are compared stripped, because the chunker runs its whitespace pass
    over those columns as well as over the text — five titles in this release carry a trailing
    space, and the row is meant to store the same string the chunk's first line shows.
    """
    for chunk in chunks:
        identity = index.get(chunk.control_id)

        assert identity is not None
        assert chunk.control_label == identity.label.strip()
        assert chunk.base_control_id == identity.base_id
        assert chunk.title == identity.title.strip()
        assert index.get(chunk.base_control_id) is not None


def test_every_live_control_and_enhancement_is_chunked_exactly_once(
    catalog: Catalog, chunks: tuple[Chunk, ...]
) -> None:
    """The count is compared against the pin rather than against a literal, because the pin is
    already the place that declares what a correct copy of the catalog contains — and its own
    comment reads `live` as the number of records the chunker should produce.

    The ticket's criterion says "every control and enhancement". The answer is every live one:
    the 182 withdrawn records are in the document and out of the corpus, and the test below says
    why that is not a gap.
    """
    live = [control.id for control in catalog.iter_controls() if not control.withdrawn]
    chunked = [chunk.control_id for chunk in chunks]

    assert len(chunked) == len(set(chunked))
    assert chunked == live
    assert len(chunked) == get_catalog_pin().expected_counts.live


def test_no_withdrawn_control_reaches_the_corpus(
    catalog: Catalog, chunks: tuple[Chunk, ...]
) -> None:
    """Nearly all of them are empty shells pointing at the control that absorbed them, so a chunk
    for one is a document that cannot be a right answer to any question but can still be returned
    instead of one. They stay resolvable — that is `ControlIndex`'s job, and it is what lets a
    stale citation be reported as stale rather than as invented."""
    withdrawn = {control.id for control in catalog.iter_controls() if control.withdrawn}
    chunked = {chunk.control_id for chunk in chunks}

    assert withdrawn
    assert not withdrawn & chunked


def test_no_chunk_contains_a_parameter_marker(chunks: tuple[Chunk, ...]) -> None:
    """Parameter resolution's criterion, re-asserted on the other side of chunking. Resolution
    guarantees it for the strings it is handed; this is what guarantees the chunker hands it all
    of them."""
    for chunk in chunks:
        assert "{{" not in chunk.text
        assert "}}" not in chunk.text
        assert "insert:" not in chunk.text


def test_the_corpus_holds_only_the_statement_and_the_guidance(
    catalog: Catalog, chunks: tuple[Chunk, ...]
) -> None:
    """Assessment objectives and methods are excluded rather than folded in or chunked
    separately, and the embedding comparison was measured with them out.

    Two assertions rather than one, because neither is sufficient alone. `part_path` is the
    structural claim: only the `_smt` and `_gdn` parts contributed to any chunk. The size ratio
    is the claim that this is worth doing — resolving every part of every live control produces
    2,019,535 characters of prose against the corpus's 1,007,525.

    Deliberately not asserted by looking for assessment prose inside a chunk. Two obvious
    versions of that are both wrong: "Determine if" reads like assessment voice and opens
    SI-2(2)'s actual control statement, and 13 assessment objectives quote their control's
    statement verbatim, so a substring test fails on text that belongs in the corpus.
    """
    resolver = ParameterResolver.for_catalog(catalog)
    chunked = {chunk.control_id for chunk in chunks}

    every_part = sum(
        len(resolver.resolve(part.prose))
        for control in catalog.iter_controls()
        if control.id in chunked
        for part in control.iter_parts()
        if part.prose
    )
    corpus = sum(len(chunk.text) for chunk in chunks)

    for chunk in chunks:
        assert chunk.part_path == ONLY_PART_PATH

    assert every_part / corpus == pytest.approx(2.0, abs=0.1)


def test_the_identifier_and_the_statement_precede_the_discussion(
    chunks: tuple[Chunk, ...],
) -> None:
    """The whole of the long-control rule, expressed as an assertion rather than only as prose.

    The pinned model's window is 512 tokens and 26 of these chunks exceed it. Nothing is split,
    so what makes that a bounded loss rather than an unknown one is the assembly order: a cut at
    any length removes the tail of the discussion and never the identifier, the title or the
    control statement. See `docs/decisions/chunking.md`.

    The head is composed from the stored columns without adjustment, which is a second claim:
    five titles in this release carry a trailing space — `SA-4(7) NIAP-approved Protection
    Profiles ` — and the columns go through the same whitespace pass the text does, so a citation
    rendered from a row reads exactly as the chunk it came from opens.
    """
    for chunk in chunks:
        control = chunk.text.index("\n\nControl:\n")
        discussion = chunk.text.index("\n\nDiscussion:\n")

        assert chunk.text.startswith(f"{chunk.control_label} {chunk.title}")
        assert control < discussion


def test_chunking_is_deterministic(catalog: Catalog, chunks: tuple[Chunk, ...]) -> None:
    """Same catalog and same version in, byte-identical chunks out. Order included: the sequence
    comes from the document, and nothing in the chunk path iterates a set or a dictionary."""
    again = chunk_catalog(catalog)

    assert again == chunks
    assert [chunk.chunk_id for chunk in again] == [chunk.chunk_id for chunk in chunks]


def test_the_chunker_version_and_fingerprint_are_pinned(catalog: Catalog) -> None:
    """An assembly change that nobody announced fails here rather than downstream, where it would
    show up as a corpus whose vectors no longer describe it."""
    assert CHUNKER_VERSION == "1"
    assert chunker_fingerprint(catalog) == EXPECTED_FINGERPRINT


def test_a_chunk_id_is_not_a_control_id(chunks: tuple[Chunk, ...], index: ControlIndex) -> None:
    """They are different keys and joining on the wrong one has to fail loudly rather than
    quietly work. A chunk id is also not one of the catalog's own part ids: `ac-2:smt+gdn` uses a
    separator no part id contains, so the two spaces cannot be confused."""
    for chunk in chunks:
        assert chunk.chunk_id != chunk.control_id
        assert chunk.chunk_id == f"{chunk.control_id}:{chunk.part_path}"
        assert index.resolve(chunk.chunk_id) is None

    assert len({chunk.chunk_id for chunk in chunks}) == len(chunks)


def test_clause_lettering_survives_into_the_chunk(chunks: tuple[Chunk, ...]) -> None:
    """Control text refers to its own clauses by their lettering, so prose stripped of it loses
    the thing a reviewer clicking through is looking for."""
    chunk = next(chunk for chunk in chunks if chunk.control_id == "ac-2")

    assert "\na. Define and document" in chunk.text


def _catalog(*controls: Control) -> Catalog:
    return Catalog(
        uuid="uuid",
        title="title",
        version="version",
        last_modified="last-modified",
        oscal_version="oscal-version",
        groups=(Group(id="xx", title="Example", class_=None, controls=controls, parts=()),),
    )


def _part(name: str, prose: str | None, part_id: str | None = None) -> Part:
    return Part(id=part_id, name=name, title=None, prose=prose, label=None, parts=())


def _control(*parts: Part, withdrawn: bool = False, control_id: str = "xx-1") -> Control:
    return Control(
        id=control_id,
        title="Example",
        class_="SP800-53",
        label="XX-1",
        zero_padded_label="XX-01",
        sort_id="xx-01",
        group_id="xx",
        withdrawn=withdrawn,
        params=(),
        parts=parts,
        enhancements=(),
    )


def test_a_live_control_with_no_included_prose_is_refused() -> None:
    """Unreachable in this release, where all 1,014 live controls carry both parts. Emitting the
    title alone would put a document in the corpus that says nothing, and it would do so
    silently."""
    with pytest.raises(ChunkingError, match="no statement or guidance"):
        chunk_catalog(_catalog(_control(_part("assessment-objective", "Determine if:"))))


def test_a_control_carrying_only_one_included_part_says_so_in_its_part_path() -> None:
    """`part_path` is computed from the parts present rather than hardcoded, so it stops being
    constant the moment the catalog stops giving every control both."""
    (chunk,) = chunk_catalog(_catalog(_control(_part("statement", "Do the thing.", "xx-1_smt"))))

    assert chunk.part_path == "smt"
    assert chunk.chunk_id == "xx-1:smt"
    assert chunk.text == "XX-1 Example\n\nControl:\nDo the thing."


def test_a_part_without_an_id_falls_back_to_its_name() -> None:
    """Every included part in this release carries one. A release that stopped publishing them
    should produce a readable part path rather than an empty one."""
    (chunk,) = chunk_catalog(_catalog(_control(_part("guidance", "Some discussion."))))

    assert chunk.part_path == "guidance"
    assert chunk.chunk_id == "xx-1:guidance"


def test_the_whitespace_rules_the_pinned_release_does_not_exercise_still_work() -> None:
    """Three of the five fire on nothing in this catalog: a non-breaking space, a run of spaces,
    and a run of blank lines. They are kept as cover for a release that varies, and a rule kept
    for that reason and never executed is decoration — worse, it can break silently, since no
    corpus-wide assertion would notice. The non-breaking space is the sharp case: it is written
    as an escape precisely because an editor turning it back into an ordinary space would leave
    the rule reading correctly and doing nothing.
    """
    # Written as `chr` rather than as the character, for the same reason the module writes
    # it as an escape: a non-breaking space pasted into a test is invisible, and a test
    # nobody can read is not evidence that the rule works.
    prose = f"First{chr(0xA0)}line  with   runs.\n\n\n\nSecond line. "
    (chunk,) = chunk_catalog(_catalog(_control(_part("statement", prose, "xx-1_smt"))))

    assert chunk.text == "XX-1 Example\n\nControl:\nFirst line with runs.\n\nSecond line."


def test_a_blank_line_carrying_a_space_is_collapsed_like_an_empty_one() -> None:
    """The likeliest way the blank-line rule's shape would actually arrive.

    A `\\n{3,}` collapse run before line ends are stripped does not match a blank line holding a
    space, so a rule kept as cover for a release that varies would miss the variation. The spaces
    are spelled out in the string rather than left to a reader to infer, for the same reason the
    non-breaking space above is written as an escape.
    """
    prose = "First line." + "\n \n \n \n" + "Second line."
    (chunk,) = chunk_catalog(_catalog(_control(_part("statement", prose, "xx-1_smt"))))

    assert chunk.text == "XX-1 Example\n\nControl:\nFirst line.\n\nSecond line."


def test_the_assembly_order_is_imposed_rather_than_taken_from_the_document() -> None:
    """No control in the pinned release publishes its guidance before its statement, and the
    no-split rule would be unsound for one that did: the 512-token cut would fall through the
    requirement instead of through the tail of the discussion, with nothing objecting. The order
    is `INCLUDED_PARTS`', so a release that reversed the two produces the same chunk.
    """
    (chunk,) = chunk_catalog(
        _catalog(
            _control(
                _part("guidance", "Some discussion.", "xx-1_gdn"),
                _part("statement", "Do the thing.", "xx-1_smt"),
            )
        )
    )

    assert chunk.text == "XX-1 Example\n\nControl:\nDo the thing.\n\nDiscussion:\nSome discussion."
    assert chunk.part_path == ONLY_PART_PATH


def test_the_fingerprint_covers_identifiers_and_not_only_text() -> None:
    """A chunk silently changing which control it is labelled with has to be as visible as its
    prose changing, so the digest is taken over every field rather than over the text.

    The two catalogs differ in the control's id and in nothing else — same label, same title,
    same prose — so they produce byte-identical chunk text. The pinned release cannot contain
    that shape, and it is the only one that tells a digest over every field apart from a digest
    over `text` alone.
    """
    part = _part("statement", "Do the thing.", "xx-1_smt")
    baseline = _catalog(_control(part))
    renumbered = _catalog(_control(part, control_id="xx-2"))

    (original,) = chunk_catalog(baseline)
    (moved,) = chunk_catalog(renumbered)

    assert original.text == moved.text
    assert original.control_id != moved.control_id
    assert chunker_fingerprint(renumbered) != chunker_fingerprint(baseline)


def test_a_withdrawn_control_with_prose_is_still_excluded() -> None:
    """Two withdrawn controls in the pinned release do carry a statement, so "withdrawn" and
    "empty" are not the same test and exclusion cannot rest on the prose being absent."""
    withdrawn = _control(_part("statement", "Text.", "xx-1_smt"), withdrawn=True)

    assert chunk_catalog(_catalog(withdrawn)) == ()
